### ISSUE TITLE
Could not get the code sample working.

### ISSUE THREAD

**Issue by CodFront** [atomashpolskiy/bt#115]
A noob here. Imported the library in a Maven project with dependencies listed in the Usage section of README. The application compiles all right, but running it does not show anything in the console except some errors (not exceptions...just text in red) from sl4j indicating a class load error. Pasting the exact message:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. 
```
After printing the above three lines, the app does nothing. Doesn't even exit.
The code:

```import bt.Bt;
import bt.data.Storage;
import bt.data.file.FileSystemStorage;
import bt.dht.DHTConfig;
import bt.dht.DHTModule;
import bt.runtime.BtClient;
import bt.runtime.Config;
import com.google.inject.Module;

import java.io.File;
import java.nio.file.Path;

public class Main {
    public static void main(String[] args) {
        // enable multithreaded verification of torrent data
        Config config = new Config() {
            @Override
            public int getNumOfHashingThreads() {
                return Runtime.getRuntime().availableProcessors() * 2;
            }
        };

        Module dhtModule = new DHTModule(new DHTConfig() {
            @Override
            public boolean shouldUseRouterBootstrap() {
                return true;
            }
        });

        Path targetDirectory = new File("D://blah").toPath();

        Storage storage = new FileSystemStorage(targetDirectory);

        BtClient client = Bt.client()
                .config(config)
                .storage(storage)
                .magnet("magnet:?xt=urn:btih:af0d9aa01a9ae123a73802cfa58ccaf355eb19f1")
                .autoLoadModules()
                .module(dhtModule)
                .stopWhenDownloaded()
                .build();

        client.startAsync().join();
    }
}
```

I'm using OpenJDK 1.8.0.212-1 (32-bit) on a Windows 10 (64-bit machine).

If I let the program run long enough (5-10 minutes maybe) without exiting...it throws the following exception:

```
java.nio.file.AccessDeniedException: C:\Users\{user-name}\AppData\Local\Temp\unlink-test1322319146828006858.tmp
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at the8472.utils.AnonAllocator.<clinit>(AnonAllocator.java:30)
	at lbms.plugins.mldht.kad.Node.saveTable(Node.java:885)
	at lbms.plugins.mldht.kad.DHT.lambda$started$16(DHT.java:819)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
...and then again sits idle and does nothing. I have to manually kill the app from within IDE in order to exit it.

**Comment by atomashpolskiy** [comment]
Try adding `org.slf4j:slf4j-simple` to your project's dependencies (https://www.slf4j.org/manual.html)

**Comment by CodFront** [comment]
My pom.xml looks like this:

````
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test-torrent</groupId>
    <artifactId>test-torrent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.github.atomashpolskiy</groupId>
            <artifactId>bt-core</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>com.github.atomashpolskiy</groupId>
            <artifactId>bt-http-tracker-client</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>com.github.atomashpolskiy</groupId>
            <artifactId>bt-dht</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>com.github.atomashpolskiy</groupId>
            <artifactId>bt-upnp</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.21</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
````
Confirmed that slf4j api and slf4j implementation have same versions, rebuilt the project in Intellij Idea but still getting the same results. A question, should it behave like so even if no implementation was found? I mean, clearly something is wrong with the logger but should that prevent the app from downloading anything at all?

**Comment by CodFront** [comment]
Never mind...I got it. Overlooked the fact that scope was set to test. BTW, while downloading the torrent I keep getting these IOException:

```ERROR bt.net.DataReceivingLoop - Failed to process key
java.lang.RuntimeException: Unexpected I/O error
	at bt.net.pipeline.SocketChannelHandler.read(SocketChannelHandler.java:83)
	at bt.net.pipeline.DefaultChannelPipeline$DefaultChannelHandlerContext.fireChannelReady(DefaultChannelPipeline.java:192)
	at bt.net.DataReceivingLoop.processKey(DataReceivingLoop.java:161)
	at bt.net.DataReceivingLoop.run(DataReceivingLoop.java:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at bt.net.pipeline.SocketChannelHandler.processInboundData(SocketChannelHandler.java:136)
	at bt.net.pipeline.SocketChannelHandler.read(SocketChannelHandler.java:80)
	... 6 more
```
They don't stop the download. Is this normal?

**Comment by atomashpolskiy** [comment]
Yes

**Comment by CodFront** [comment]
Closing the issue. Thanks!
