### ISSUE TITLE
Integration of the library with Android

### ISSUE THREAD

**Issue by master255** [atomashpolskiy/bt#140]
What exactly are the libraries needed to run all bt components on an Android?
I have an error in this place:
BtRuntime runtime = BtRuntime.builder(config).module(dhtModule).autoLoadModules().build();
error:
java.lang.ExceptionInInitializerError
        at com.google.inject.internal.cglib.core.$MethodWrapper.create(MethodWrapper.java:34)
        at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:25)
        at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:231)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:252)
        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:203)
        at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:69)

My code:
```
Config config = new Config();
            config.setAcceptorPort(37000 + new Random().nextInt(20000));
            config.setNumOfHashingThreads(Runtime.getRuntime().availableProcessors() * 2);
            DHTModule dhtModule = new DHTModule(new DHTConfig() {
                public int getListeningPort() {
                    return config.getAcceptorPort();
                }

                public boolean shouldUseRouterBootstrap() {
                    return true;
                }
            });
            BtRuntime runtime = BtRuntime.builder(config).module(dhtModule).autoLoadModules().build();
            Storage storage = new FileSystemStorage(new File(proxyParams.getTempFileName()));
            PieceSelector selector = SequentialSelector.sequential();
            BtClientBuilder clientBuilder = Bt.client(runtime).storage(storage).selector(selector);
//            clientBuilder.afterTorrentFetched(this.processor::whenTorrentFetched);
//            clientBuilder.afterFilesChosen(this.processor::onFilesChosen);
            TorrentFile file = new TorrentFile() {
                @Override
                public long getSize() {
                    return proxyParams.getTorrentFile().getFileLength();
                }

                @Override
                public List<String> getPathElements() {
                    return proxyParams.getTorrentFile().getFileDirs();
                }
            };
            Torrent torrent = new Torrent() {
                @Override
                public TorrentSource getSource() {
                    return null;
                }

                @Override
                public Optional<AnnounceKey> getAnnounceKey() {
                    return Optional.of(new AnnounceKey(new ArrayList<>(Arrays.asList(proxyParams.getTorrentFile().getAnnounceList()))));
                }

                @Override
                public TorrentId getTorrentId() {
                    return TorrentId.fromBytes(hexStringToByteArray(proxyParams.getTorrentFile().getInfoHash()));
                }

                @Override
                public String getName() {
                    return proxyParams.getTorrentFile().getFileName();
                }

                @Override
                public long getChunkSize() {
                    return proxyParams.getTorrentFile().getPieceLength();
                }

                @Override
                public Iterable<byte[]> getChunkHashes() {
                    return null;
                }

                @Override
                public long getSize() {
                    return proxyParams.getTorrentFile().getFileLength();
                }

                @Override
                public List<TorrentFile> getFiles() {
                    return Arrays.asList(file);
                }

                @Override
                public boolean isPrivate() {
                    return false;
                }

                @Override
                public Optional<Instant> getCreationDate() {
                    return Optional.empty();
                }

                @Override
                public Optional<String> getCreatedBy() {
                    return Optional.empty();
                }
            };
            clientBuilder.torrent(() -> torrent);
            btClient = clientBuilder.build();
            btClient.startAsync();
```

**Comment by atomashpolskiy** [comment]
Looks the same as https://github.com/atomashpolskiy/bt/issues/112

**Comment by master255** [comment]
@atomashpolskiy I use:
implementation project(path: ':bt-upnp-1.10-SNAPSHOT')
    implementation project(path: ':bt-dht-1.10-SNAPSHOT')
    implementation project(path: ':bt-core-1.10-SNAPSHOT')
    implementation project(path: ':javax.inject-1')
    implementation project(path: ':guice-multibindings-4.1.0')
    implementation project(path: ':guice-4.1.0')
    implementation project(path: ':bt-http-tracker-client-1.10-SNAPSHOT')
and:
![Снимок](https://user-images.githubusercontent.com/5380115/76453752-75e72f80-63e4-11ea-81dc-83c31531ad1d.PNG)
Which versions of libraries are not correct? Which libraries are redundant?

**Comment by atomashpolskiy** [comment]
Can you try bumping Guice version to e.g. 4.2.2 or higher? Seems like 4.1.0
does not work on Android

**Comment by master255** [comment]
@atomashpolskiy after upgrading guice to version 4.2.2, the following error occurred:
java.lang.NoSuchMethodError: No static method checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V in class Lcom/google/common/base/Preconditions; or its super classes (declaration of 'com.google.common.base.Preconditions' appears in /data/app/com.media.library-yPcobZuSJw8Zwe4PXOfBKw==/base.apk)
        at com.google.inject.internal.MoreTypes$ParameterizedTypeImpl.ensureOwnerType(MoreTypes.java:435)
        at com.google.inject.internal.MoreTypes$ParameterizedTypeImpl.<init>(MoreTypes.java:359)
        at com.google.inject.internal.MoreTypes.canonicalize(MoreTypes.java:159)
        at com.google.inject.TypeLiteral.getSuperclassTypeParameter(TypeLiteral.java:98)
        at com.google.inject.TypeLiteral.<init>(TypeLiteral.java:75)
        at bt.module.ProtocolModuleExtender$2.<init>(ProtocolModuleExtender.java:139)
        at bt.module.ProtocolModuleExtender.contributeMessageHandlers(ProtocolModuleExtender.java:135)
        at bt.module.ProtocolModuleExtender.initAllExtensions(ProtocolModuleExtender.java:48)
        at bt.module.ProtocolModule.configure(ProtocolModule.java:120)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
        at com.google.inject.util.Modules$CombinedModule.configure(Modules.java:128)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
        at com.google.inject.spi.Elements.getElements(Elements.java:103)

**Comment by master255** [comment]
Thank you for the answers. I made my own library for downloading torrents. It didn't turn out to be difficult.
Besides, your library doesn't support Android below version 8. And I need support from version 4.3.
Goodbye.

**Comment by CombustibleIce** [comment]
> Thank you for the answers. I made my own library for downloading torrents. It didn't turn out to be difficult. Besides, your library doesn't support Android below version 8. And I need support from version 4.3. Goodbye.

hello,have you solved it on Android?

**Comment by master255** [comment]
@CombustibleIce Yes. I use Libtorrent
