### ISSUE TITLE
[BUG] parse magnets with 'spaces' problem.

### ISSUE THREAD

**Issue by RumoEL** [atomashpolskiy/bt#154]
magnet:?xt=urn:btih:HASH&dn=Word1 Word2

[MagnetLinkFileReader](https://github.com/RumoEL/rumo-pas/blob/6063bdc2ca135def9299c770e257b6b460f3c8d7/bittorrentspy/src/main/java/com/github/rumoel/pas/bittorrentspy/dht/MagnetLinkFileReader.java#L48)

java.lang.IllegalArgumentException: Invalid URI: magnet:?xt=urn:btih:HASH&dn=Word1 Word2
        at bt.magnet.MagnetUriParser.parse(MagnetUriParser.java:94)
        at com.github.rumoel.pas.bittorrentspy.dht.MagnetLinkFileReader.lambda$readFromFile$0(MagnetLinkFileReader.java:48)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.github.rumoel.pas.bittorrentspy.dht.MagnetLinkFileReader.readFromFile(MagnetLinkFileReader.java:53)
        at com.github.rumoel.pas.bittorrentspy.v3.trackers.impl.TrackerDHT.init(TrackerDHT.java:73)
        at com.github.rumoel.pas.bittorrentspy.v3.trackers.TrackerHandler.init(TrackerHandler.java:24)
        at com.github.rumoel.pas.bittorrentspy.v3.init.PBSInit.main(PBSInit.java:31)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index (Word1#HERE#Word2): magnet:?xt=urn:btih:HASH&dn=Word1 Word2
        at java.base/java.net.URI$Parser.fail(URI.java:2913)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
        at java.base/java.net.URI$Parser.parse(URI.java:3120)
        at java.base/java.net.URI.<init>(URI.java:600)
        at bt.magnet.MagnetUriParser.parse(MagnetUriParser.java:92)

**Comment by atomashpolskiy** [comment]
Magnet is a type of URI, so parameters must be escaped.

**Comment by RumoEL** [comment]
1)is urlencode ok?
2)or use '\ ' ?
3)or & dn = "Word1 Word2"
4)%26dn%3DWord1+Word2? 
what to use?

**Comment by atomashpolskiy** [comment]
Yes, URL encode (%20)

**Comment by atomashpolskiy** [comment]
And only parameters, not the uri itself (i.e. '&' in parameter value must
be encoded, but & delimiter must not)

**Comment by RumoEL** [comment]
Thanks for the clarification.
I don't know how to remove the 'bug' label.
we close this issue
