### ISSUE TITLE
[BUG] springboot use

### ISSUE THREAD

**Issue by pangoo-reuse** [atomashpolskiy/bt#203]
bug like this
`2022-04-19 10:05:53.649  INFO 2050 --- [0.1-8090-exec-2] bt.runtime.BtRuntimeBuilder              : Loading standard extension module bt.peer.lan.LocalServiceDiscoveryModule
2022-04-19 10:05:53.650  INFO 2050 --- [0.1-8090-exec-2] bt.runtime.BtRuntimeBuilder              : Loading standard extension module bt.peerexchange.PeerExchangeModule
2022-04-19 10:05:53.650  INFO 2050 --- [0.1-8090-exec-2] bt.runtime.BtRuntimeBuilder              : Overriding auto-loaded module bt.dht.DHTModule
2022-04-19 10:05:53.650  INFO 2050 --- [0.1-8090-exec-2] bt.runtime.BtRuntimeBuilder              : Auto-loading module bt.portmapping.upnp.UpnpPortMapperModule with default configuration
2022-04-19 10:05:53.650  INFO 2050 --- [0.1-8090-exec-2] bt.runtime.BtRuntimeBuilder              : Auto-loading module bt.tracker.http.HttpTrackerModule with default configuration
2022-04-19 10:05:54.171  INFO 2050 --- [0.1-8090-exec-2] b.n.p.impl.PortMappingInitializer        : Mapping application's acceptor port on startup.
2022-04-19 10:05:54.200  INFO 2050 --- [ming-acceptor-0] bt.net.SocketChannelConnectionAcceptor   : Opening server channel for incoming connections @ /192.168.0.104:6891
2022-04-19 10:05:54.209  INFO 2050 --- [0.1-8090-exec-2] org.fourthline.cling.UpnpServiceImpl     : >>> Starting UPnP service...
2022-04-19 10:05:54.209  INFO 2050 --- [0.1-8090-exec-2] org.fourthline.cling.UpnpServiceImpl     : Using configuration: bt.portmapping.upnp.jetty.JettyAsyncUpnpServiceConfiguration
2022-04-19 10:05:54.215  INFO 2050 --- [0.1-8090-exec-2] org.fourthline.cling.transport.Router    : Creating Router: org.fourthline.cling.transport.RouterImpl
2022-04-19 10:05:54.220  INFO 2050 --- [0.1-8090-exec-2] o.f.c.transport.spi.MulticastReceiver    : Creating wildcard socket (for receiving multicast datagrams) on port: 1900
2022-04-19 10:05:54.229  INFO 2050 --- [0.1-8090-exec-2] o.f.c.transport.spi.MulticastReceiver    : Joining multicast group: /239.255.255.250:1900 on network interface: en0
2022-04-19 10:05:54.241  INFO 2050 --- [0.1-8090-exec-2] org.eclipse.jetty.util.log               : Logging initialized @16340ms to org.eclipse.jetty.util.log.Slf4jLog
2022-04-19 10:05:54.251  INFO 2050 --- [tartup.worker-1] org.fourthline.cling.UpnpServiceImpl     : >>> Starting UPnP service...
2022-04-19 10:05:54.252  INFO 2050 --- [tartup.worker-1] org.fourthline.cling.UpnpServiceImpl     : Using configuration: bt.portmapping.upnp.jetty.JettyAsyncUpnpServiceConfiguration
2022-04-19 10:05:54.252  INFO 2050 --- [tartup.worker-1] org.fourthline.cling.transport.Router    : Creating Router: org.fourthline.cling.transport.RouterImpl
2022-04-19 10:05:54.253  INFO 2050 --- [tartup.worker-1] o.f.c.transport.spi.MulticastReceiver    : Creating wildcard socket (for receiving multicast datagrams) on port: 1900
2022-04-19 10:05:54.254  INFO 2050 --- [tartup.worker-1] o.f.c.transport.spi.MulticastReceiver    : Joining multicast group: /239.255.255.250:1900 on network interface: en0
2022-04-19 10:05:54.258 ERROR 2050 --- [0.1-8090-exec-2] bt.runtime.BtRuntime                     : Error on runtime startup

bt.BtException: Failed to execute startup hook: : bt.net.portmapping.impl.PortMappingInitializer$$Lambda$1337/0x000000080146dad8@7ad98cac
	at bt.runtime.BtRuntime.lambda$runHooks$3(BtRuntime.java:265) ~[bt-core-1.10.jar:1.10]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at bt.runtime.BtRuntime.runHooks(BtRuntime.java:260) ~[bt-core-1.10.jar:1.10]
	at bt.runtime.BtRuntime.startup(BtRuntime.java:157) ~[bt-core-1.10.jar:1.10]
	at bt.DefaultClient.ensureRuntimeStarted(DefaultClient.java:136) ~[bt-core-1.10.jar:1.10]
	at bt.DefaultClient.doStartAsync(DefaultClient.java:100) ~[bt-core-1.10.jar:1.10]
	at bt.DefaultClient.startAsync(DefaultClient.java:96) ~[bt-core-1.10.jar:1.10]
	at bt.LazyClient.startAsync(LazyClient.java:55) ~[bt-core-1.10.jar:1.10]
	at com.smart.torrent.Torrent.torr(Torrent.java:52) ~[classes/:na]
	at com.smart.mall.controller.TorrentController.startDownload(TorrentController.java:17) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.16.jar:5.3.16]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.16.jar:5.3.16]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.16.jar:5.3.16]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.16.jar:5.3.16]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.16.jar:5.3.16]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.16.jar:5.3.16]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.16.jar:5.3.16]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.16.jar:5.3.16]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.16.jar:5.3.16]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.16.jar:5.3.16]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-embed-core-9.0.58.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.16.jar:5.3.16]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.58.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at com.smart.mall.interceptor.GzipFilter.doFilter(GzipFilter.java:34) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at com.smart.mall.interceptor.AppFilter.doFilter(AppFilter.java:54) ~[classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.16.jar:5.3.16]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.16.jar:5.3.16]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.58.jar:9.0.58]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.NoSuchMethodError: 'void org.eclipse.jetty.server.Server.setGracefulShutdown(int)'
	at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.resetServer(JettyServletContainer.java:166) ~[cling-core-2.1.1.jar:na]
	at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.<init>(JettyServletContainer.java:57) ~[cling-core-2.1.1.jar:na]
	at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.<clinit>(JettyServletContainer.java:55) ~[cling-core-2.1.1.jar:na]
	at bt.portmapping.upnp.jetty.JettyAsyncUpnpServiceConfiguration.createStreamServer(JettyAsyncUpnpServiceConfiguration.java:46) ~[bt-upnp-1.10.jar:1.10]
	at org.fourthline.cling.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:427) ~[cling-core-2.1.1.jar:na]
	at org.fourthline.cling.transport.RouterImpl.enable(RouterImpl.java:132) ~[cling-core-2.1.1.jar:na]
	at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87) ~[cling-core-2.1.1.jar:na]
	at bt.portmapping.upnp.UpnpPortMappingServicesRegistrar.registerPortMapping(UpnpPortMappingServicesRegistrar.java:55) ~[bt-upnp-1.10.jar:1.10]
	at bt.portmapping.upnp.UpnpPortMapper.mapPort(UpnpPortMapper.java:51) ~[bt-upnp-1.10.jar:1.10]
	at bt.net.portmapping.impl.PortMappingInitializer.mapPort(PortMappingInitializer.java:53) ~[bt-core-1.10.jar:1.10]
	at bt.net.portmapping.impl.PortMappingInitializer.lambda$null$0(PortMappingInitializer.java:48) ~[bt-core-1.10.jar:1.10]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at bt.net.portmapping.impl.PortMappingInitializer.lambda$new$1(PortMappingInitializer.java:48) ~[bt-core-1.10.jar:1.10]
	at bt.runtime.BtRuntime.lambda$toRunnable$7(BtRuntime.java:324) ~[bt-core-1.10.jar:1.10]
	at bt.runtime.BtRuntime.lambda$runHooks$3(BtRuntime.java:263) ~[bt-core-1.10.jar:1.10]
	... 57 common frames omitted

2022-04-19 10:06:09.230  WARN 2050 --- [.peer-collector] bt.peer.ScheduledPeerSource              : Peer collection finished with exception in peer source: TrackerPeerSource {UdpTracker{trackerUrl=http://tracker.leechers-paradise.org:6969}}

java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[na:na]
	at bt.peer.ScheduledPeerSource.waitForFutureAndLogExceptions(ScheduledPeerSource.java:101) ~[bt-core-1.10.jar:1.10]
	at bt.peer.ScheduledPeerSource.schedulePeerCollection(ScheduledPeerSource.java:86) ~[bt-core-1.10.jar:1.10]
	at bt.peer.ScheduledPeerSource.update(ScheduledPeerSource.java:66) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.queryPeerSource(PeerRegistry.java:199) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.queryTracker(PeerRegistry.java:177) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.lambda$queryTrackers$6(PeerRegistry.java:165) ~[bt-core-1.10.jar:1.10]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at bt.peer.PeerRegistry.queryTrackers(PeerRegistry.java:163) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.collectPeersForTorrent(PeerRegistry.java:144) ~[bt-core-1.10.jar:1.10]
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[na:na]
	at bt.peer.PeerRegistry.collectAndVisitPeers(PeerRegistry.java:114) ~[bt-core-1.10.jar:1.10]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-04-19 10:06:20.504  WARN 2050 --- [.peer-collector] bt.peer.ScheduledPeerSource              : Peer collection finished with exception in peer source: TrackerPeerSource {UdpTracker{trackerUrl=http://tracker.empire-js.us:1337}}

java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[na:na]
	at bt.peer.ScheduledPeerSource.waitForFutureAndLogExceptions(ScheduledPeerSource.java:101) ~[bt-core-1.10.jar:1.10]
	at bt.peer.ScheduledPeerSource.schedulePeerCollection(ScheduledPeerSource.java:86) ~[bt-core-1.10.jar:1.10]
	at bt.peer.ScheduledPeerSource.update(ScheduledPeerSource.java:66) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.queryPeerSource(PeerRegistry.java:199) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.queryTracker(PeerRegistry.java:177) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.lambda$queryTrackers$6(PeerRegistry.java:165) ~[bt-core-1.10.jar:1.10]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at bt.peer.PeerRegistry.queryTrackers(PeerRegistry.java:163) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.collectPeersForTorrent(PeerRegistry.java:144) ~[bt-core-1.10.jar:1.10]
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[na:na]
	at bt.peer.PeerRegistry.collectAndVisitPeers(PeerRegistry.java:114) ~[bt-core-1.10.jar:1.10]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-04-19 10:06:30.863  WARN 2050 --- [.peer-collector] bt.peer.ScheduledPeerSource              : Peer collection finished with exception in peer source: TrackerPeerSource {UdpTracker{trackerUrl=http://tracker.coppersurfer.tk:6969}}

java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[na:na]
	at bt.peer.ScheduledPeerSource.waitForFutureAndLogExceptions(ScheduledPeerSource.java:101) ~[bt-core-1.10.jar:1.10]
	at bt.peer.ScheduledPeerSource.schedulePeerCollection(ScheduledPeerSource.java:86) ~[bt-core-1.10.jar:1.10]
	at bt.peer.ScheduledPeerSource.update(ScheduledPeerSource.java:66) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.queryPeerSource(PeerRegistry.java:199) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.queryTracker(PeerRegistry.java:177) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.lambda$queryTrackers$6(PeerRegistry.java:165) ~[bt-core-1.10.jar:1.10]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at bt.peer.PeerRegistry.queryTrackers(PeerRegistry.java:163) ~[bt-core-1.10.jar:1.10]
	at bt.peer.PeerRegistry.collectPeersForTorrent(PeerRegistry.java:144) ~[bt-core-1.10.jar:1.10]
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[na:na]
	at bt.peer.PeerRegistry.collectAndVisitPeers(PeerRegistry.java:114) ~[bt-core-1.10.jar:1.10]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-04-19 10:06:40.874  WARN 2050 --- [.peer-collector] bt.peer.ScheduledPeerSource              : Peer collection finished with exception in peer source: TrackerPeerSource {UdpTracker{trackerUrl=http://tracker.opentrackr.org:1337}}
`

**Comment by atomashpolskiy** [comment]
There seems to be incompatibility of the UPnP module with the version of
Jetty that you use in your web app. Just remove the dependency on bt-upnp
module.
