### ISSUE TITLE
Question: Failing UDP trackers: Failed to receive response from the tracker

### ISSUE THREAD

**Issue by Raudius** [atomashpolskiy/bt#5]
Hello,
I'm completely new to the bittorrent protocol so I'm probably doing a million things wrong.

The trouble is I can't seem to get any response from UDP trackers. HTTP trackers however work fine.
This has been the case with other libraries that I have tried, so it is likely there is nothing wrong with the implementation. Any ideas how to solve this? 

Thanks,
Raudius

```
bt.BtException: Failed to receive response from the tracker
	at bt.tracker.udp.UdpMessageWorker.sendMessage(UdpMessageWorker.java:80)
	at bt.tracker.udp.UdpMessageWorker.sendMessage(UdpMessageWorker.java:82)
	at bt.tracker.udp.UdpMessageWorker.createSession(UdpMessageWorker.java:67)
	at bt.tracker.udp.UdpMessageWorker.getSession(UdpMessageWorker.java:61)
	at bt.tracker.udp.UdpMessageWorker.sendMessage(UdpMessageWorker.java:56)
	at bt.tracker.udp.UdpTracker$1.announceEvent(UdpTracker.java:109)
	at bt.tracker.udp.UdpTracker$1.start(UdpTracker.java:81)
	at bt.tracker.MultiTracker$1.lambda$0(MultiTracker.java:61)
	at bt.tracker.MultiTracker$1.tryForAllTrackers(MultiTracker.java:111)
	at bt.tracker.MultiTracker$1.start(MultiTracker.java:61)
	at bt.torrent.DefaultTorrentDescriptor.start(DefaultTorrentDescriptor.java:44)
	at bt.DefaultClient.doStart(DefaultClient.java:76)
	at bt.DefaultClient.startAsync(DefaultClient.java:70)
	at bt.RuntimeAwareClient.startAsync(RuntimeAwareClient.java:30)
	at bt.LazyClient.startAsync(LazyClient.java:39)
	at com.canariapp.flixseek.torrentget.TorrentManager.addTorrent(TorrentManager.java:34)
	at com.canariapp.flixseek.torrentget.TorrentManager.main(TorrentManager.java:65)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at bt.tracker.udp.UdpMessageWorker.sendMessage(UdpMessageWorker.java:75)
	... 16 more
```

**Comment by atomashpolskiy** [comment]
Hi @Raudius ! Thanks for sharing! Yeah, it does seem like the tracker itself is not responding. Considering that `bt.tracker.MultiTracker` is involved in the stack, there should be an `announce-list` property in the torrent file. Bt should try announcing to all trackers in this list. Is this the only tracker-related exception in out.log?

**Comment by Raudius** [comment]
OK so I just realised that HTTP trackers don't work with this library (as they havent been implemented yet(?)). I was able to get those to work through ttorrent. 

But with when starting the client I also get this line of output:
```
1124 [bt.net.pool.incoming-acceptor] INFO bt.net.PeerConnectionPool - Opening server channel for incoming connections @ /192.168.1.40:6891
```
Which sugggests that it is listening only for connections locally? Shouldnt that be my public address instead?

Then after that line and after the tracker connection times out I get the error in the first post, and it repeats it after each timeout preceded by the error:
```
151120 [bt.peer.peer-collector] ERROR bt.peer.PeerRegistry - Error when querying peer source: bt.peer.TrackerPeerSource@2456c2b9
```

**Comment by atomashpolskiy** [comment]
HTTP trackers are supported, but for the sake of keeping the core with minimum number of 3-rd party dependencies it's shipped as a separate module.

Include this in your pom.xml:
```
<dependency>
    <groupId>com.github.atomashpolskiy</groupId>
    <artifactId>bt-core</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>com.github.atomashpolskiy</groupId>
    <artifactId>bt-http-tracker-client</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>
```

Then create your client in the following way:
```
BtRuntime runtime = BtRuntime.builder().module(new HttpTrackerModule()).build();
```

Or
```
BtRuntime runtime = BtRuntime.builder().module(new HttpTrackerModule()).module(new PeerExchangeModule()).build();
```
if you also want to make use of peer exchange.

You might also want to look through the brief explanation of basic concepts, it should help build a better picture of the main API:
http://atomashpolskiy.github.io/bt/intro/

**Comment by atomashpolskiy** [comment]
> But with when starting the client I also get this line of output:
`1124 [bt.net.pool.incoming-acceptor] INFO bt.net.PeerConnectionPool - Opening server channel for incoming connections @ /192.168.1.40:6891`
Which sugggests that it is listening only for connections locally? Shouldnt that be my public address instead?

Nope, it's listening on a local port. Peers will be able to contact you via your external address, which will be communicated to them by the tracker, that you are working with.
