### ISSUE TITLE
Cant download anything - nat?

### ISSUE THREAD

**Issue by faljse** [atomashpolskiy/bt#89]
Im having issues downloading anything with version 1.7 or 1.8 snapshot

My internet connection is double nated - so incomming connections will not work.
Shouldnt it be still be possible to download a well seeded torrent?

**Comment by faljse** [comment]
I mean i got a router (nat) which connects to a lte stick with internal nat.
And i assume the provider also does cgn.

There is no chance of providing an outside reachable port; however other torrent clients (qbittorrent) are able to download files.

I have read the faq; im using jdk10, which has unlimited crypto stuff und i did force ipv4

The torrent is current ubuntu iso.. so there should be enougn public seeders

There are some exceptions on startup, but i couldnt figure out if they are relevant
```
[bt.runtime.startup-worker-1] ERROR bt.dht.MldhtService - Unexpected DHT error
java.io.IOException: /192.168.56.1 -> router.bittorrent.com/67.215.246.10:6881 while attempting to send  Method:PING Type:REQ_MSG MessageID:0x64B6903B210A/d��;!�  
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:800)
	at lbms.plugins.mldht.kad.RPCServer.fillPipe(RPCServer.java:562)
	at lbms.plugins.mldht.kad.RPCServer.dispatchCall(RPCServer.java:579)
	at lbms.plugins.mldht.kad.RPCServer.drainQueue(RPCServer.java:270)
	at the8472.utils.concurrent.SerializedTaskExecutor.lambda$onceMore$2(SerializedTaskExecutor.java:71)
	at lbms.plugins.mldht.kad.RPCServer.doCall(RPCServer.java:226)
	at lbms.plugins.mldht.kad.RPCServer.ping(RPCServer.java:312)
	at lbms.plugins.mldht.kad.DHT.addDHTNode(DHT.java:526)
	at bt.dht.MldhtService.addNode(MldhtService.java:224)
	at bt.dht.MldhtService.addNode(MldhtService.java:220)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at bt.dht.MldhtService.start(MldhtService.java:160)
	at bt.runtime.BtRuntime.lambda$toRunnable$7(BtRuntime.java:309)
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.DatagramChannelImpl.send0(Native Method)
	at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:483)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462)
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:757)
	... 17 more
Aug 19, 2018 10:51:10 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: <<< UPnP service started successfully
[bt.runtime.startup-worker-1] ERROR bt.dht.MldhtService - Unexpected DHT error
java.io.IOException: /192.168.56.1 -> dht.transmissionbt.com/87.98.162.88:6881 while attempting to send  Method:PING Type:REQ_MSG MessageID:0x878141909E7F/��A���  
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:800)
	at lbms.plugins.mldht.kad.RPCServer.fillPipe(RPCServer.java:562)
	at lbms.plugins.mldht.kad.RPCServer.dispatchCall(RPCServer.java:579)
	at lbms.plugins.mldht.kad.RPCServer.drainQueue(RPCServer.java:270)
	at the8472.utils.concurrent.SerializedTaskExecutor.lambda$onceMore$2(SerializedTaskExecutor.java:71)
	at lbms.plugins.mldht.kad.RPCServer.doCall(RPCServer.java:226)
	at lbms.plugins.mldht.kad.RPCServer.ping(RPCServer.java:312)
	at lbms.plugins.mldht.kad.DHT.addDHTNode(DHT.java:526)
	at bt.dht.MldhtService.addNode(MldhtService.java:224)
	at bt.dht.MldhtService.addNode(MldhtService.java:220)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at bt.dht.MldhtService.start(MldhtService.java:160)
	at bt.runtime.BtRuntime.lambda$toRunnable$7(BtRuntime.java:309)
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.DatagramChannelImpl.send0(Native Method)
	at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:483)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462)
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:757)
	... 17 more
[bt.runtime.startup-worker-1] ERROR bt.dht.MldhtService - Unexpected DHT error
java.io.IOException: /192.168.56.1 -> router.utorrent.com/82.221.103.244:6881 while attempting to send  Method:PING Type:REQ_MSG MessageID:0x18355A55AD4C/�5ZU�L  
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:800)
	at lbms.plugins.mldht.kad.RPCServer.fillPipe(RPCServer.java:562)
	at lbms.plugins.mldht.kad.RPCServer.dispatchCall(RPCServer.java:579)
	at lbms.plugins.mldht.kad.RPCServer.drainQueue(RPCServer.java:270)
	at the8472.utils.concurrent.SerializedTaskExecutor.lambda$onceMore$2(SerializedTaskExecutor.java:71)
	at lbms.plugins.mldht.kad.RPCServer.doCall(RPCServer.java:226)
	at lbms.plugins.mldht.kad.RPCServer.ping(RPCServer.java:312)
	at lbms.plugins.mldht.kad.DHT.addDHTNode(DHT.java:526)
	at bt.dht.MldhtService.addNode(MldhtService.java:224)
	at bt.dht.MldhtService.addNode(MldhtService.java:220)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at bt.dht.MldhtService.start(MldhtService.java:160)
	at bt.runtime.BtRuntime.lambda$toRunnable$7(BtRuntime.java:309)
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.DatagramChannelImpl.send0(Native Method)
	at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:483)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462)
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:757)
	... 17 more
Aug 19, 2018 10:51:10 PM org.fourthline.cling.UpnpServiceImpl <init>
```

**Comment by atomashpolskiy** [comment]
```
ERROR bt.dht.MldhtService - Unexpected DHT error
java.io.IOException: /192.168.56.1 -> router.bittorrent.com/67.215.246.10:6881 while attempting to send  Method:PING Type:REQ_MSG MessageID:0x64B6903B210A/d��;!�  
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:800)
	at lbms.plugins.mldht.kad.RPCServer.fillPipe(RPCServer.java:562)
	at lbms.plugins.mldht.kad.RPCServer.dispatchCall(RPCServer.java:579)
	at lbms.plugins.mldht.kad.RPCServer.drainQueue(RPCServer.java:270)
	at the8472.utils.concurrent.SerializedTaskExecutor.lambda$onceMore$2(SerializedTaskExecutor.java:71)
	at lbms.plugins.mldht.kad.RPCServer.doCall(RPCServer.java:226)
	at lbms.plugins.mldht.kad.RPCServer.ping(RPCServer.java:312)
	at lbms.plugins.mldht.kad.DHT.addDHTNode(DHT.java:526)
	at bt.dht.MldhtService.addNode(MldhtService.java:224)
	at bt.dht.MldhtService.addNode(MldhtService.java:220)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at bt.dht.MldhtService.start(MldhtService.java:160)
	at bt.runtime.BtRuntime.lambda$toRunnable$7(BtRuntime.java:309)
	at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Network is unreachable: no further information
```
This error is most probably caused by JVM binding to IPv6 address. It should not happen when using `-Djava.net.preferIPv4Stack=true`, unless there are network connectivity issues on your machine.

> There is no chance of providing an outside reachable port

You should still be able to reach out to seeders. Are you getting any peers from the tracker and/or DHT? Are there any log messages about connecting to peers?

**Comment by faljse** [comment]
Thx for the hint; i re-checked the ipv4 option, and it was definitely set.

BUT.. disabling my "virtualbox host only networking" interface makes the exception disappear and it starts to download.

Havent had time yet to debug this further...

**Comment by atomashpolskiy** [comment]
Bt networking binds to the first suitable interface [by default](https://github.com/atomashpolskiy/bt/blob/master/bt-core/src/main/java/bt/service/NetworkUtil.java#L38). So if you have multiple network interfaces, it's possible to explicitly specify the IP address to bind to in the [BitTorrent config](https://github.com/atomashpolskiy/bt/blob/master/bt-core/src/main/java/bt/runtime/Config.java#L135). DHT, on the other hand, has a separate [strategy](https://github.com/atomashpolskiy/bt/blob/master/bt-dht/the8472/mldht/src/lbms/plugins/mldht/kad/RPCServerManager.java) for choosing bind addresses, which does not allow to provide a specific address in the configuration. It does allow multihoming though, which is currently always turned off by [Bt DHT adapter](https://github.com/atomashpolskiy/bt/blob/master/bt-dht/bt-dht/src/main/java/bt/dht/MldhtService.java#L132). Seems like turning it on might be the correct way to resolve your issue. This will require adding a new option `allowMultihoming` in the [DHT config](https://github.com/atomashpolskiy/bt/blob/master/bt-dht/bt-dht/src/main/java/bt/dht/DHTConfig.java).

**Comment by atomashpolskiy** [comment]
In fact DHT module supports [filtering](https://github.com/atomashpolskiy/bt/blob/master/bt-dht/the8472/mldht/src/lbms/plugins/mldht/DHTConfiguration.java#L38) of bind addresses. Still requires a change in the adapter config though.

**Comment by luismance** [comment]
I don't think the DHTConfig does not have the allowMultihoming option

**Comment by atomashpolskiy** [comment]
I checked the code once more, and it turns out that the filtering of bind addresses has already been done. See [here](https://github.com/atomashpolskiy/bt/blob/master/bt-dht/bt-dht/src/main/java/bt/dht/MldhtService.java#L137). In short, DHT is bound to the same address as the main BitTorrent node.

**Comment by vikulin** [comment]
@atomashpolskiy This method does not work in <bt-version>1.7</bt-version>:
18:01:51.771 [bt.net.pool.incoming-acceptor-0] ERROR bt.net.IncomingConnectionListener - Unexpected error
java.lang.RuntimeException: Failed to create incoming connection acceptor -- unexpected I/O exception happened when creating an incoming channel
	at bt.net.SocketChannelConnectionAcceptor.accept(SocketChannelConnectionAcceptor.java:86) ~[bt-core-1.7.jar:1.7]
	at bt.net.IncomingConnectionListener.lambda$null$0(IncomingConnectionListener.java:60) ~[bt-core-1.7.jar:1.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_181]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_181]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_181]
	at java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:157) ~[?:1.8.0_181]
	at bt.net.SocketChannelConnectionAcceptor.getServerChannel(SocketChannelConnectionAcceptor.java:122) ~[bt-core-1.7.jar:1.7]
	at bt.net.SocketChannelConnectionAcceptor.accept(SocketChannelConnectionAcceptor.java:83) ~[bt-core-1.7.jar:1.7]
	... 6 more
18:01:52.732 [bt.runtime.startup-worker-1] ERROR bt.dht.MldhtService - Unexpected DHT error
java.io.IOException: /192.168.138.1 -> router.bittorrent.com/67.215.246.10:6881 while attempting to send  Method:PING Type:REQ_MSG MessageID:0x39D750E48509/9�P���  
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:800) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.fillPipe(RPCServer.java:562) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.dispatchCall(RPCServer.java:579) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.drainQueue(RPCServer.java:270) ~[bt-dht-1.7.jar:?]
	at the8472.utils.concurrent.SerializedTaskExecutor.lambda$onceMore$2(SerializedTaskExecutor.java:71) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.doCall(RPCServer.java:226) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.ping(RPCServer.java:312) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.DHT.addDHTNode(DHT.java:526) ~[bt-dht-1.7.jar:?]
	at bt.dht.MldhtService.addNode(MldhtService.java:205) ~[bt-dht-1.7.jar:?]
	at bt.dht.MldhtService.addNode(MldhtService.java:201) ~[bt-dht-1.7.jar:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880) ~[?:1.8.0_181]
	at bt.dht.MldhtService.start(MldhtService.java:154) ~[bt-dht-1.7.jar:?]
	at bt.runtime.BtRuntime.lambda$toRunnable$6(BtRuntime.java:309) ~[bt-core-1.7.jar:1.7]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.DatagramChannelImpl.send0(Native Method) ~[?:1.8.0_181]
	at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521) ~[?:1.8.0_181]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:483) ~[?:1.8.0_181]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462) ~[?:1.8.0_181]
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:757) ~[bt-dht-1.7.jar:?]
	... 16 more
18:01:52.738 [bt.runtime.startup-worker-1] ERROR bt.dht.MldhtService - Unexpected DHT error
java.io.IOException: /192.168.138.1 -> dht.transmissionbt.com/87.98.162.88:6881 while attempting to send  Method:PING Type:REQ_MSG MessageID:0x5CC535DAAFC2/\�5���  
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:800) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.fillPipe(RPCServer.java:562) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.dispatchCall(RPCServer.java:579) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.drainQueue(RPCServer.java:270) ~[bt-dht-1.7.jar:?]
	at the8472.utils.concurrent.SerializedTaskExecutor.lambda$onceMore$2(SerializedTaskExecutor.java:71) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.doCall(RPCServer.java:226) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.ping(RPCServer.java:312) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.DHT.addDHTNode(DHT.java:526) ~[bt-dht-1.7.jar:?]
	at bt.dht.MldhtService.addNode(MldhtService.java:205) ~[bt-dht-1.7.jar:?]
	at bt.dht.MldhtService.addNode(MldhtService.java:201) ~[bt-dht-1.7.jar:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880) ~[?:1.8.0_181]
	at bt.dht.MldhtService.start(MldhtService.java:154) ~[bt-dht-1.7.jar:?]
	at bt.runtime.BtRuntime.lambda$toRunnable$6(BtRuntime.java:309) ~[bt-core-1.7.jar:1.7]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.DatagramChannelImpl.send0(Native Method) ~[?:1.8.0_181]
	at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521) ~[?:1.8.0_181]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:483) ~[?:1.8.0_181]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462) ~[?:1.8.0_181]
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:757) ~[bt-dht-1.7.jar:?]
	... 16 more
18:01:52.738 [bt.runtime.startup-worker-1] ERROR bt.dht.MldhtService - Unexpected DHT error
java.io.IOException: /192.168.138.1 -> router.utorrent.com/82.221.103.244:6881 while attempting to send  Method:PING Type:REQ_MSG MessageID:0xAF3799C3DEE5/�7����  
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:800) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.fillPipe(RPCServer.java:562) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.dispatchCall(RPCServer.java:579) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.drainQueue(RPCServer.java:270) ~[bt-dht-1.7.jar:?]
	at the8472.utils.concurrent.SerializedTaskExecutor.lambda$onceMore$2(SerializedTaskExecutor.java:71) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.doCall(RPCServer.java:226) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.RPCServer.ping(RPCServer.java:312) ~[bt-dht-1.7.jar:?]
	at lbms.plugins.mldht.kad.DHT.addDHTNode(DHT.java:526) ~[bt-dht-1.7.jar:?]
	at bt.dht.MldhtService.addNode(MldhtService.java:205) ~[bt-dht-1.7.jar:?]
	at bt.dht.MldhtService.addNode(MldhtService.java:201) ~[bt-dht-1.7.jar:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880) ~[?:1.8.0_181]
	at bt.dht.MldhtService.start(MldhtService.java:154) ~[bt-dht-1.7.jar:?]
	at bt.runtime.BtRuntime.lambda$toRunnable$6(BtRuntime.java:309) ~[bt-core-1.7.jar:1.7]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.DatagramChannelImpl.send0(Native Method) ~[?:1.8.0_181]
	at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521) ~[?:1.8.0_181]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:483) ~[?:1.8.0_181]
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462) ~[?:1.8.0_181]
	at lbms.plugins.mldht.kad.RPCServer$SocketHandler.writeEvent(RPCServer.java:757) ~[bt-dht-1.7.jar:?]
	... 16 more
