### ISSUE TITLE
java.nio.file.AccessDeniedException: C:\Users\Dhaval\AppData\Local\Temp\unlink-test574818207068815219.tmp

### ISSUE THREAD

**Issue by dhaval-mehta** [atomashpolskiy/bt#90]
I got following exception.

Maven, Java and OS info:
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T00:03:14+05:30)
Maven home: C:\Program Files\apache\maven\bin\..
Java version: 1.8.0_162, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_162\jre
Default locale: en_IN, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

StackTrace:

java.nio.file.AccessDeniedException: C:\Users\Dhaval\AppData\Local\Temp\unlink-test574818207068815219.tmp
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
        at java.nio.file.Files.delete(Unknown Source)
        at the8472.utils.AnonAllocator.<clinit>(AnonAllocator.java:30)
        at lbms.plugins.mldht.kad.Node.saveTable(Node.java:885)
        at lbms.plugins.mldht.kad.DHT.stop(DHT.java:869)
        at bt.dht.MldhtService.shutdown(MldhtService.java:183)
        at bt.runtime.BtRuntime.lambda$toRunnable$7(BtRuntime.java:309)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by atomashpolskiy** [comment]
A more descriptive error message has been added, see [here](https://github.com/atomashpolskiy/bt/blob/master/bt-dht/the8472/mldht/src/the8472/utils/AnonAllocator.java#L39)
